version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ../../app
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    container_name: db
    build: 
      context: ../../db
      dockerfile: Dockerfile
    env_file:
      - ../../.env
    ports:
      - '5432:5432'

  rabbitmq:
    image: 'rabbitmq:management'
    container_name: swms_rabbitmq_container
    ports:
      - '15672:15672' # management UI
      - '5672:5672' # default RabbitMQ listener port
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'adminpassword'
      RABBITMQ_DEFAULT_VHOST: '/'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
    restart: always

  pdfgenerator:
    platform: linux/arm64/v8
    build:
      context: ../../pdf
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ../../.env
    depends_on:
      - rabbitmq

volumes:
  nginx:
  rabbitmq_data:
